export default {
    authenticated:false,
    userEmail: '',
    novaobjava: '',
    postovi: [],
    naslov: '',
    znj:[],
    ime:'',
    prezime:'',
    kontakt:'',
    tip:'',
    brojdjece:'',
    grad: '',
    gradovi:['Bjelovar','Čakovec','Dubrovnik','Gospić','Karlovac','Koprivnica','Krapina','Osijek','Pazin','Požega','Pula','Rijeka', 'Sisak','Slavonski Brod','Split','Šibenik','Varaždin','Vinkovci','Virovitica','Vukovar', 'Zadar','Zagreb'],
    iskustvo: '',
    ostalo:'',
    spol:'',
    mjestocuvanjadjece:'',
    brojgodina: '',
    dozvola: '',
    searchterm:'',
    brojac: true,

}